#,##0;(#,##0.00)

Strain summary count
```{r prep}
library(readr)
library(caret)
library(readxl)
library(xlsx)


name5 <- function(x) {
  x <- gsub("VersicolorNRRL226", "AmoenusNRRL226", x)
  return(tolower(substr(x, 1, 5)))
}


df_sum <- read_xlsx("~/Chenyang/img_summary.xlsx")
df_sum$aname<- gsub("Aspergillus", "A.", df_sum$species)
df_sum$name5 <- gsub("Aspergillus ", "", df_sum$species)
df_sum$name5 <- sapply(df_sum$name5, name5)
 
cy_name <- read_csv("~/Chenyang/Dens201-only crop-20201118/Ambiguity List.csv")[,4]
cy_name <- unique.data.frame(cy_name)
cy_name$Likeliest <- gsub("VersicolorNRRL226", "AmoenusNRRL226", cy_name$Likeliest)
cy_name$name5 <- sapply(cy_name$Likeliest, name5)

df_sum <- merge.data.frame(df_sum, cy_name)
df_sum$sname <- paste(df_sum$aname, df_sum$strain)
df_cy2a <- df_sum[, c("name5", "aname", "sname")]
df_cy2a <- unique.data.frame(df_cy2a)


cy2a <- function(x) {
  x <- gsub("VersicolorNRRL226", "AmoenusNRRL226", x)
  return(df_cy2a$aname[df_cy2a$name5==x][1])
}


cy2st <- function(x) {
  x <- gsub("VersicolorNRRL226", "AmoenusNRRL226", x)
  x <- gsub("NRRL", " NRRL", x)
  x <- gsub("ATCC", " ATCC", x)
  x <- gsub("CBS", " CBS", x)
  x <- gsub("AF", " AF", x)
  x <- gsub("QC", " QC", x)
  x <- paste("A.", x)
  return(x)
}
```


```{r}
folder_list <- paste0("~/Chenyang/Dens201-only crop-20201118/")#, c("densenet201", "inceptionv3", "res50"), "/")
prob_paths <- paste0(folder_list, "Y_pred&Probs.xlsx")
N_file <- length(prob_paths)
sp <- unique(df_sum$aname)
sp_actual <- rep(df_sum$aname, df_sum$test_img)
st_count <- c(2, 2, 2, 4, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1)
N_sp <- length(st_count)

for (i in 1:N_file){
  #df_st <- read_excel(prob_paths[i], sheet = 2, col_names = F)
  df_st <- read_csv("~/Chenyang/Dens201-only crop-20201118/Y_Pred_probs.csv", col_names = F)
  df_sp <- data.frame(rep(0, nrow(df_st))) # placeholder column of 175 zeros
  for (j in 1:N_sp) {
    df_sp_temp <- df_st[,1:st_count[j]]
    df_st <- df_st[,-(1:st_count[j])]
    df_sp[,(j + 1)] <- rowSums(df_sp_temp)
  }
  df_sp <- df_sp[, -1]
  colnames(df_sp) <- sp
  write_excel_csv(df_sp, paste0(folder_list[i], "aggregated Y_pred&probs.csv"))
}


for (i in 1:N_file) {
  df_sp <- read_csv(paste0(folder_list[i], "aggregated Y_pred&probs.csv"))
  
  pred <- character()
  prob <- numeric()
  pred2 <- character()
  prob2 <- numeric()
 
  for (j in 1:nrow(df_sp)) {
    probs <- sort(df_sp[j,], decreasing = T)[1:2]
    preds <- colnames(probs)
    probs <- as.numeric(probs) * 100
    
    pred <- append(pred, preds[1])
    prob <- append(prob, probs[1])
    
    pred2 <- append(pred2, preds[2])
    prob2 <- append(prob2, probs[2])    
  }
  
  df_amb <- data.frame(1:nrow(df_sp), sp_actual, pred, prob, pred2, prob2)
  df_amb$Ambiguity <- df_amb$prob2/df_amb$prob
  df_amb$wrong <- df_amb$pred != df_amb$sp_actual
  
  colnames(df_amb)[1] <- "Image number"
  
  #write_excel_csv(df_amb, paste0(folder_list[i], "aggregated ambiguity.csv"))
  write_excel_csv(df_amb, paste0(folder_list[i], "aggregated ambiguity.csv"))
}
```


```{r}
folder_list <- paste0("~/Chenyang/Dens201-only crop-20201118/")#, c("densenet201", "inceptionv3", "res50"), "/")
prob_paths <- paste0(folder_list, "aggregated ambiguity.csv")

for (i in 1:3) {
  df_temp <- read_csv(prob_paths[i])
  tbl <- table(df_temp$pred, df_temp$sp_actual)
  cm <- confusionMatrix(tbl)
  write.xlsx(as.data.frame.matrix(tbl), paste0(folder_list[i], "cmat.xlsx"))
  write_csv(data.frame(cm$byClass), paste0(folder_list[i], "cmat_byclass.csv"))
}

```
