---
title: "t-SNE prep"
output: html_document
---

#,##0;(#,##0.00)


```{r t-SNE set up}
library(readr)
library(readxl)


df_sum <- read_xlsx("~/Chenyang/img_summary.xlsx")
#df_sum$strain <- paste(df_sum$species, df_sum$strain)
actual_sp <- rep(df_sum$species, df_sum$test_img)
actual_st <- rep(df_sum$strain, df_sum$test_img)


n_st <- as.numeric(table(df_sum$species))
st2 <- numeric()
for (i in 1:length(n_st)) {
  st2 <- append(st2, 1:n_st[i])
}


# adj for amoenus not sorting
st2 <- st2[-3]
st2[length(st2)+1] <- 1


actual_st2 <- rep(st2, df_sum$test_img)
#colours <- c("#FF0000", "#F00000", "magenta","orange", "orange2", "grey50", "grey75", "yellow", "yellow1", "yellow2", "yellow3", "dimgray", "gold", "wheat1", "#00FF00", "#00F000", "blue", "blue2", "khaki", "khaki2", "lightblue", "lightblue2", "pink", "pink2", "darkseagreen", "darkseagreen2", "darkblue")


sp_col <- c("lightslateblue", "brown4", "pink", "chartreuse4", "deepskyblue3", "#B5995B", "#789078", "#000000", "#FF0000", "cyan", "#76654C", "khaki3", "chartreuse", "magenta", "orange")
st_shapes <- c(16, 15, 18, 17)
```



```{r load matlab output}
library(R.matlab)


#df_pred <- readMat("~/Chenyang/Results_aug_20200918/densenet201/dens201_20200920.mat")
df_pred <- readMat("~/Chenyang/Results_aug_20200918/inceptionv3/incepv3_20200920.mat")
#df_pred <- readMat("~/Chenyang/Results_aug_20200918/res50/res50_20200918.mat")


conv_act <- df_pred$finalConvActivations
sm_act <- df_pred$softmaxActivations
```



```{r custom t-SNE plot}
library(Rtsne)
library(ggplot2)
library(ggiraph)


plot_tsne <- function(act, per, dim) {
  tsne_temp <- Rtsne(act, perplexity = per)
  df_tsne <- data.frame(tsne_temp$Y)
  df_tsne$sp <- factor(actual_sp)
  df_tsne$st <- factor(actual_st)
  df_tsne$st2 <- factor(actual_st2)
  gg_obj <- ggplot(df_tsne) + geom_point_interactive(aes(X1, X2, colour = sp, shape = st2, tooltip = st2, data_id = 1:175), size = 4, show.legend = F) + scale_colour_manual(values = sp_col) + scale_shape_manual(values = st_shapes) + theme_classic()
  hello <- girafe(gg_obj = gg_obj)
  if (interactive()) {
    print(hello)
  }
}
```



```{r}
plot_tsne(conv_act, 40)
plot_tsne(conv_act, 45)
plot_tsne(conv_act, 50)


plot_tsne(sm_act, 40)
plot_tsne(sm_act, 45)
plot_tsne(sm_act, 50)


tsne_temp <- Rtsne(sm_act, perplexity = 50)
df_temp <- data.frame(tsne_temp$Y)
df_temp$xdist <- df_temp$X1 - df_temp$X1[141]
df_temp$ydist <- df_temp$X2 - df_temp$X2[141]
df_temp$dist <- sqrt(df_temp$xdist^2 + df_temp$ydist^2)




tsne_temp <- Rtsne(sm_act, perplexity = 50)
df_tsne <- data.frame(tsne_temp$Y)
df_tsne$sp <- factor(actual_sp)
df_tsne$st <- factor(actual_st)
df_tsne$st2 <- factor(actual_st2)
ggplot(df_tsne) + geom_point_interactive(aes(X1, X2, colour = sp, shape = st2, tooltip = st2, data_id = 1:175), size = 4, show.legend = F) + scale_colour_manual(values = sp_col) + scale_shape_manual(values = st_shapes) + theme_classic()

View(df_tsne)
```

